### ISSUE TITLE
Execution fails with error and return code 1

### ISSUE THREAD

**Issue by AmrSaber** [marmelab/json-graphql-server#100]
**What you were expecting:**
To run the server

**What happened instead:**
I get the following error:
```
/path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:1
TypeError: e.reduce is not a function
    at A (/path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:95:1352841)
    at P (/path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:95:1353043)
    at /path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:95:1354046
    at Array.map (<anonymous>)
    at /path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:95:1353965
    at V (/path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:95:1354096)
    at Z (/path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:95:1361152)
    at t.default (/path-to-project/node_modules/json-graphql-server/lib/json-graphql-server.node.min.js:95:1361270)
    at Object.<anonymous> (/path-to-project/src/__mocks__/serve.js:8:21)
    at Generator.next (<anonymous>)
error Command failed with exit code 1.
```

**Steps to reproduce:**
Install the package then try to run it with a simple structure like the following...
```js
module.exports = {
  store: {
    name: 'some store',
    id: '123'
  }
};
```

and it will fail.

**Other information:**

**Environment**
OS: Ubuntu 18.04
Node version: 14.15.3
Yarn version: 1.22.10
Npm Version: 6.14.7 (I installed the package with yarn, execution fails with both yarn and npm)

**Comment by AmrSaber** [comment]
I am sorry, this is my mistake, I didn't realize that all root fields must be arrays, updating the example to 
```js
module.exports = {
  stores: [{
    name: 'some store',
    id: '123'
  }]
};
```
Got things working.
