### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by Hyllesen** [marmelab/json-graphql-server#23]
Sorry but I'm not exactly sure how I am supposed to run this.

I've run ```npm install -g json-graphql-server```

I've cloned this repo locally using ```git clone https://github.com/marmelab/json-graphql-server.git```then I ran ```yarn install``` inside the directory.

Now when I run ```json-graphql-server data.js```inside the ```example``` folder I get the error below.
I have tried to create my own db.js file using the example in the readme as well, giving the same result.

```Stefans-iMac:example stefanhyltoft$ json-graphql-server data.js
/usr/local/lib/node_modules/json-graphql-server/src/introspection/getSchemaFromData.js:174
    const schemaExtension = Object.values(typesByName).reduce((ext, type) => {
                                   ^

TypeError: Object.values is not a function
    at module.exportDefault.data (/usr/local/lib/node_modules/json-graphql-server/src/introspection/getSchemaFromData.js:174:36)
    at module.exportDefault.data (/usr/local/lib/node_modules/json-graphql-server/src/schemaBuilder.js:8:31)
    at Object.module.exportDefault.data [as jsonGraphqlExpress] (/usr/local/lib/node_modules/json-graphql-server/src/jsonGraphqlExpress.js:50:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/json-graphql-server/bin/json-graphql-server.js:17:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)```

**Comment by Hyllesen** [comment]
I solved this issue myself by upgrading my Node to the latest version 8. I was using the stable version 6 which didn't seem to have the .values functionality.
